<b> Importing Modules

In [358]:
import pandas as pd
import numpy as np

<b> Importing Datasets

In [359]:
train_df = pd.read_csv('house_train.csv', index_col=0)
test_df = pd.read_csv('house_test.csv', index_col=0)

In [360]:
train_df.head()
train_df.shape

(1460, 80)

<b> View Missing Values

In [361]:
missing_data = train_df.isnull().sum().sort_values(ascending=False).head(20)
percentage_missing_data = train_df.isnull().sum()/train_df.isnull().count().sort_values(ascending = False) * 100
missing_values = pd.concat([missing_data, percentage_missing_data], axis=1, keys=['missing_data', 'percentage'])
missing_values.head(20)

              missing_data  percentage
PoolQC              1453.0   99.520548
MiscFeature         1406.0   96.301370
Alley               1369.0   93.767123
Fence               1179.0   80.753425
FireplaceQu          690.0   47.260274
LotFrontage          259.0   17.739726
GarageType            81.0    5.547945
GarageCond            81.0    5.547945
GarageFinish          81.0    5.547945
GarageQual            81.0    5.547945
GarageYrBlt           81.0    5.547945
BsmtFinType2          38.0    2.602740
BsmtExposure          38.0    2.602740
BsmtQual              37.0    2.534247
BsmtCond              37.0    2.534247
BsmtFinType1          37.0    2.534247
MasVnrArea             8.0    0.547945
MasVnrType             8.0    0.547945
Electrical             1.0    0.068493
RoofMatl               0.0    0.000000

In [362]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   Alley          91 non-null     object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1452 non-null   object
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1423 non-null   object
 30  BsmtCond       1423 non-null   object
 31  BsmtExposure   1422 non-null   object
 32  BsmtFinType1   1423 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    object
 57  GarageType     1379 non-null   object
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   object
 63  GarageCond     1379 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      object
 72  Fence          281 non-null    object
 73  MiscFeature    54 non-null     object
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   object
 78  SaleCondition  1460 non-null   object
 79  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(43)
memory usage: 678.7+ KB

<b> Drop Values with above 50%

In [363]:
train_df.drop(['MiscFeature', 'PoolQC', 'Alley', 'Fence'], axis=1, inplace=True)
train_df.shape

(1460, 76)

<b> Filling Missing Values

In [364]:
train_df['GarageCond'].value_counts()
train_df['FireplaceQu'].value_counts()
train_df['GarageType'].value_counts()
train_df['GarageYrBlt'].value_counts()
train_df['GarageFinish'].value_counts()
train_df['GarageQual'].value_counts()
train_df['BsmtExposure'].value_counts()
train_df['BsmtFinType2'].value_counts()
train_df['BsmtFinType1'].value_counts()
train_df['BsmtCond'].value_counts()
train_df['BsmtQual'].value_counts()
train_df['MasVnrArea'].value_counts()
train_df['MasVnrType'].value_counts()
train_df['Electrical'].value_counts()

SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

In [365]:
# Filling the numerical Null values with mean
train_df['LotFrontage'] = train_df['LotFrontage'].fillna(train_df['LotFrontage'].mean())

In [366]:
## Filling the categorical null values with mode
train_df['GarageCond'] = train_df['GarageCond'].fillna(train_df['GarageCond'].mode()[0])
train_df['FireplaceQu'] = train_df['FireplaceQu'].fillna(train_df['FireplaceQu'].mode()[0])
train_df['GarageType'] = train_df['GarageType'].fillna(train_df['GarageType'].mode()[0])
train_df['GarageYrBlt'] = train_df['GarageYrBlt'].fillna(train_df['GarageYrBlt'].mode()[0])
train_df['GarageFinish'] = train_df['GarageFinish'].fillna(train_df['GarageFinish'].mode()[0])
train_df['GarageQual'] = train_df['GarageQual'].fillna(train_df['GarageQual'].mode()[0])
train_df['BsmtExposure'] = train_df['BsmtExposure'].fillna(train_df['BsmtExposure'].mode()[0])
train_df['BsmtFinType2'] = train_df['BsmtFinType2'].fillna(train_df['BsmtFinType2'].mode()[0])
train_df['BsmtFinType1'] = train_df['BsmtFinType1'].fillna(train_df['BsmtFinType1'].mode()[0])
train_df['BsmtCond'] = train_df['BsmtCond'].fillna(train_df['BsmtCond'].mode()[0])
train_df['BsmtQual'] = train_df['BsmtQual'].fillna(train_df['BsmtQual'].mode()[0])
train_df['MasVnrArea'] = train_df['MasVnrArea'].fillna(train_df['MasVnrArea'].mode()[0])
train_df['MasVnrType'] = train_df['MasVnrType'].fillna(train_df['MasVnrType'].mode()[0])
train_df['Electrical'] = train_df['Electrical'].fillna(train_df['Electrical'].mode()[0])

In [367]:
# Checking the shape of the train dataset
train_df.shape

(1460, 76)

In [368]:
## Checking if there is a null value
train_df.isnull().sum().max()

0

In [369]:
train_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [370]:
## Handling the test dataset
test_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [371]:
missing_test_data = test_df.isnull().sum().sort_values(ascending=False)
percentage_mtd = test_df.isnull().sum()/test_df.isnull().count().sort_values(ascending=False)*100
missing_test_values = pd.concat([missing_test_data, percentage_mtd], axis=1, keys=['missing_test_data', 'percentage'])
missing_test_values.head(34)

              missing_test_data  percentage
PoolQC                     1456   99.794380
MiscFeature                1408   96.504455
Alley                      1352   92.666210
Fence                      1169   80.123372
FireplaceQu                 730   50.034270
LotFrontage                 227   15.558602
GarageCond                   78    5.346127
GarageFinish                 78    5.346127
GarageYrBlt                  78    5.346127
GarageQual                   78    5.346127
GarageType                   76    5.209047
BsmtCond                     45    3.084304
BsmtExposure                 44    3.015764
BsmtQual                     44    3.015764
BsmtFinType1                 42    2.878684
BsmtFinType2                 42    2.878684
MasVnrType                   16    1.096642
MasVnrArea                   15    1.028101
MSZoning                      4    0.274160
BsmtHalfBath                  2    0.137080
Utilities                     2    0.137080
Functional                    2    0.137080
BsmtFullBath                  2    0.137080
BsmtFinSF2                    1    0.068540
BsmtFinSF1                    1    0.068540
BsmtUnfSF                     1    0.068540
TotalBsmtSF                   1    0.068540
Exterior2nd                   1    0.068540
SaleType                      1    0.068540
Exterior1st                   1    0.068540
KitchenQual                   1    0.068540
GarageArea                    1    0.068540
GarageCars                    1    0.068540
OverallQual                   0    0.000000

In [372]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 1461 to 2919
Data columns (total 79 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1459 non-null   int64
 1   MSZoning       1455 non-null   object
 2   LotFrontage    1232 non-null   float64
 3   LotArea        1459 non-null   int64
 4   Street         1459 non-null   object
 5   Alley          107 non-null    object
 6   LotShape       1459 non-null   object
 7   LandContour    1459 non-null   object
 8   Utilities      1457 non-null   object
 9   LotConfig      1459 non-null   object
 10  LandSlope      1459 non-null   object
 11  Neighborhood   1459 non-null   object
 12  Condition1     1459 non-null   object
 13  Condition2     1459 non-null   object
 14  BldgType       1459 non-null   object
 15  HouseStyle     1459 non-null   object
 16  OverallQual    1459 non-null   int64
 17  OverallCond    1459 non-null   int64
 18  YearBuilt      1459 non-null   int64
 19  YearRemodAdd   1459 non-null   int64
 20  RoofStyle      1459 non-null   object
 21  RoofMatl       1459 non-null   object
 22  Exterior1st    1458 non-null   object
 23  Exterior2nd    1458 non-null   object
 24  MasVnrType     1443 non-null   object
 25  MasVnrArea     1444 non-null   float64
 26  ExterQual      1459 non-null   object
 27  ExterCond      1459 non-null   object
 28  Foundation     1459 non-null   object
 29  BsmtQual       1415 non-null   object
 30  BsmtCond       1414 non-null   object
 31  BsmtExposure   1415 non-null   object
 32  BsmtFinType1   1417 non-null   object
 33  BsmtFinSF1     1458 non-null   float64
 34  BsmtFinType2   1417 non-null   object
 35  BsmtFinSF2     1458 non-null   float64
 36  BsmtUnfSF      1458 non-null   float64
 37  TotalBsmtSF    1458 non-null   float64
 38  Heating        1459 non-null   object
 39  HeatingQC      1459 non-null   object
 40  CentralAir     1459 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1459 non-null   int64
 43  2ndFlrSF       1459 non-null   int64
 44  LowQualFinSF   1459 non-null   int64
 45  GrLivArea      1459 non-null   int64
 46  BsmtFullBath   1457 non-null   float64
 47  BsmtHalfBath   1457 non-null   float64
 48  FullBath       1459 non-null   int64
 49  HalfBath       1459 non-null   int64
 50  BedroomAbvGr   1459 non-null   int64
 51  KitchenAbvGr   1459 non-null   int64
 52  KitchenQual    1458 non-null   object
 53  TotRmsAbvGrd   1459 non-null   int64
 54  Functional     1457 non-null   object
 55  Fireplaces     1459 non-null   int64
 56  FireplaceQu    729 non-null    object
 57  GarageType     1383 non-null   object
 58  GarageYrBlt    1381 non-null   float64
 59  GarageFinish   1381 non-null   object
 60  GarageCars     1458 non-null   float64
 61  GarageArea     1458 non-null   float64
 62  GarageQual     1381 non-null   object
 63  GarageCond     1381 non-null   object
 64  PavedDrive     1459 non-null   object
 65  WoodDeckSF     1459 non-null   int64
 66  OpenPorchSF    1459 non-null   int64
 67  EnclosedPorch  1459 non-null   int64
 68  3SsnPorch      1459 non-null   int64
 69  ScreenPorch    1459 non-null   int64
 70  PoolArea       1459 non-null   int64
 71  PoolQC         3 non-null      object
 72  Fence          290 non-null    object
 73  MiscFeature    51 non-null     object
 74  MiscVal        1459 non-null   int64
 75  MoSold         1459 non-null   int64
 76  YrSold         1459 non-null   int64
 77  SaleType       1458 non-null   object
 78  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(25), object(43)
memory usage: 666.8+ KB

<b> Delete data with missing values more than 50%

In [373]:
test_df.drop(['PoolQC', 'Fence', 'Alley', 'MiscFeature'], axis=1, inplace=True)

In [374]:
test_df.shape

(1459, 75)

<b> Fill Missing values

In [375]:
## Fill Missing Numerical Values with mean
test_df['LotFrontage'] = test_df['LotFrontage'].fillna(test_df['LotFrontage'].mean())

In [376]:
test_df['FireplaceQu'].value_counts()
test_df['GarageCond'].value_counts()
test_df['GarageFinish'].value_counts()
test_df['GarageYrBlt'].value_counts()
test_df['GarageQual'].value_counts()
test_df['GarageType'].value_counts()
test_df['BsmtCond'].value_counts()
test_df['BsmtExposure'].value_counts()

No    951
Av    197
Gd    142
Mn    125
Name: BsmtExposure, dtype: int64

In [377]:
## Fill Missing Categorical Values with mode
test_df['FireplaceQu'] = test_df['FireplaceQu'].fillna(test_df['FireplaceQu'].mode()[0])
test_df['GarageCond'] = test_df['GarageCond'].fillna(test_df['GarageCond'].mode()[0])
test_df['GarageFinish'] = test_df['GarageFinish'].fillna(test_df['GarageFinish'].mode()[0])
test_df['GarageYrBlt'] = test_df['GarageYrBlt'].fillna(test_df['GarageYrBlt'].mode()[0])
test_df['GarageQual'] = test_df['GarageQual'].fillna(test_df['GarageQual'].mode()[0])
test_df['GarageType'] = test_df['GarageType'].fillna(test_df['GarageType'].mode()[0])
test_df['BsmtCond'] = test_df['BsmtCond'].fillna(test_df['BsmtCond'].mode()[0])
test_df['BsmtExposure'] = test_df['BsmtExposure'].fillna(test_df['BsmtExposure'].mode()[0])
test_df['BsmtQual'] = test_df['BsmtQual'].fillna(test_df['BsmtQual'].mode()[0])
test_df['BsmtFinType1'] = test_df['BsmtFinType1'].fillna(test_df['BsmtFinType1'].mode()[0])
test_df['BsmtFinType2'] = test_df['BsmtFinType2'].fillna(test_df['BsmtFinType2'].mode()[0])
test_df['MasVnrType'] = test_df['MasVnrType'].fillna(test_df['MasVnrType'].mode()[0])
test_df['MasVnrArea'] = test_df['MasVnrArea'].fillna(test_df['MasVnrArea'].mode()[0])
test_df['MSZoning'] = test_df['MSZoning'].fillna(test_df['MSZoning'].mode()[0])
test_df['BsmtHalfBath'] = test_df['BsmtHalfBath'].fillna(test_df['BsmtHalfBath'].mode()[0])
test_df['Utilities'] = test_df['Utilities'].fillna(test_df['Utilities'].mode()[0])
test_df['Functional'] = test_df['Functional'].fillna(test_df['Functional'].mode()[0])
test_df['BsmtFullBath'] = test_df['BsmtFullBath'].fillna(test_df['BsmtFullBath'].mode()[0])
test_df['BsmtFinSF2'] = test_df['BsmtFinSF2'].fillna(test_df['BsmtFinSF2'].mode()[0])
test_df['BsmtFinSF1'] = test_df['BsmtFinSF1'].fillna(test_df['BsmtFinSF1'].mode()[0])
test_df['BsmtUnfSF'] = test_df['BsmtUnfSF'].fillna(test_df['BsmtUnfSF'].mode()[0])
test_df['TotalBsmtSF'] = test_df['TotalBsmtSF'].fillna(test_df['TotalBsmtSF'].mode()[0])
test_df['Exterior2nd'] = test_df['Exterior2nd'].fillna(test_df['Exterior2nd'].mode()[0])
test_df['SaleType'] = test_df['SaleType'].fillna(test_df['SaleType'].mode()[0])
test_df['Exterior1st'] = test_df['Exterior1st'].fillna(test_df['Exterior1st'].mode()[0])
test_df['KitchenQual'] = test_df['KitchenQual'].fillna(test_df['KitchenQual'].mode()[0])
test_df['GarageArea'] = test_df['GarageArea'].fillna(test_df['GarageArea'].mode()[0])
test_df['GarageCars'] = test_df['GarageCars'].fillna(test_df['GarageCars'].mode()[0])

In [378]:
test_df.isnull().sum().max()

0

In [379]:
test_df.shape

(1459, 75)

<b> Concatenate train and test datasets

In [380]:
frames = [train_df, test_df]
full_data = pd.concat(frames, axis=0)
full_data['SalePrice']

Id
1       208500.0
2       181500.0
3       223500.0
4       140000.0
5       250000.0
          ...
2915         NaN
2916         NaN
2917         NaN
2918         NaN
2919         NaN
Name: SalePrice, Length: 2919, dtype: float64

In [381]:
full_data

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500.0
2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500.0
3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500.0
4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000.0
5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,6,2006,WD,Normal,NaN
2916,160,RM,21.0,1894,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,4,2006,WD,Abnorml,NaN
2917,20,RL,160.0,20000,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2006,WD,Abnorml,NaN
2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,700,7,2006,WD,Normal,NaN
2919,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,Mod,...,0,0,0,0,0,11,2006,WD,Normal,NaN

In [382]:
cat_columns=['MSZoning','Street','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood',
         'Condition2','BldgType','Condition1','HouseStyle','SaleType',
        'SaleCondition','ExterCond',
         'ExterQual','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2',
        'RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','Heating','HeatingQC',
         'CentralAir',
         'Electrical','KitchenQual','Functional',
         'FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive']
len(cat_columns)

39

In [383]:
full_data = pd.get_dummies(full_data)

In [384]:
full_data.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
4,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
5,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0

In [385]:
full_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 1 to 2919
Columns: 276 entries, MSSubClass to SaleCondition_Partial
dtypes: float64(12), int64(25), uint8(239)
memory usage: 1.5 MB

In [386]:
df_train = full_data.iloc[:1460, :]
df_test = full_data.iloc[1460:,:]

In [387]:
df_train.shape

(1460, 276)

In [388]:
df_test.shape

(1459, 276)

In [389]:
df_test['SalePrice'].isnull().sum()
# df_test['SalePrice'].head(50)

1459

In [390]:
df_train.SalePrice.isnull().sum()

0

In [391]:
df_test.drop(['SalePrice'], axis=1, inplace=True)

C:\Users\geogr\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [392]:
df_test.shape

(1459, 275)

In [393]:
df_train['SalePrice']

Id
1       208500.0
2       181500.0
3       223500.0
4       140000.0
5       250000.0
          ...
1456    175000.0
1457    210000.0
1458    266500.0
1459    142125.0
1460    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [394]:
y_train = df_train['SalePrice']
y_train.head()
y_train.shape

(1460,)

In [395]:
x_train = df_train.drop(['SalePrice'], axis=1)
x_train.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
4,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
5,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0

In [396]:
x_train.shape

(1460, 275)

In [397]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression(fit_intercept=False)
reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [398]:
reg.coef_

array([-4.27291472e+01,  5.84263273e+01,  7.47723862e-01,  6.38041541e+03,
        5.75724872e+03,  3.10311787e+02,  9.07309493e+01,  2.03116421e+01,
        1.60684691e+01,  5.72298349e+00, -3.48335693e+00,  1.83080930e+01,
        1.83207775e+01,  3.36591827e+01, -1.88201124e+01,  3.31598496e+01,
        6.98658896e+02, -5.05666354e+02,  3.88406568e+03,  1.08277955e+03,
       -3.41587542e+03, -1.26096459e+04,  9.32103365e+02,  2.80390544e+03,
        4.42555598e+01,  3.13834589e+03,  1.39606820e+01,  1.34467984e+01,
        5.37797535e+00,  5.17773688e+00,  3.17241573e+01,  2.92856049e+01,
        8.43000292e+01,  6.94635912e-02, -4.44562574e+02, -4.18662981e+02,
       -2.78128144e+04,  7.02161053e+03, -1.16026148e+03,  6.39904102e+02,
       -3.47105595e+03, -2.77632351e+04,  2.98061783e+03, -8.58310797e+03,
       -4.89946520e+03, -4.61888643e+03, -6.68115765e+03, -7.68736160e+03,
        1.04295289e+03, -1.68509786e+04, -1.28722996e+03,  3.90495113e+03,
       -2.86875684e+04, -2.24729986e+03,  6.72735180e+03, -9.82478392e+03,
       -1.61080741e+04, -3.32981118e+03,  4.29169782e+03,  1.07247635e+04,
       -3.97990785e+04,  1.69681721e+03,  2.00581721e+03,  2.05167403e+03,
       -2.09371383e+03, -1.16091237e+04, -8.44898993e+03,  1.36979949e+04,
       -1.80741190e+04, -1.02841610e+04, -7.79000887e+03, -3.49725297e+03,
       -1.97543517e+04, -1.42439709e+04,  1.63259261e+04, -1.62819708e+04,
        2.78418060e+04,  1.92086242e+04, -1.14763786e+04, -5.92697963e+03,
       -9.40719049e+03, -2.79487509e+03, -8.41544050e+01,  3.98035344e+04,
       -8.27426829e+03,  2.62669803e+03, -6.56593455e+03, -5.21417013e+02,
        8.27523619e+03, -1.46604066e+03,  5.84923410e+03, -2.27882870e+04,
        1.08951459e+03, -8.68274570e+03,  2.78228094e+01,  4.26433010e+04,
        3.55359017e+04,  3.48849899e+04,  7.70418002e+04, -1.97771066e+05,
       -8.38179875e+04,  2.26632587e+04,  4.40371845e+04,  4.19401228e+03,
        8.68595327e+02, -2.97654377e+03, -1.48408408e+04, -1.20278403e+04,
       -1.68325619e+03,  1.16786155e+04,  6.24163067e+03, -2.66036049e+04,
       -9.62753881e+03, -6.96943602e+03,  9.70125599e+02,  1.21084689e+03,
       -2.72206289e+04, -2.05491861e+04, -1.69340355e+04, -2.05988138e+04,
       -9.16384570e+03,  6.96838928e+04, -6.14538450e+05,  5.67189857e+04,
        1.50057563e+05,  1.21827336e+05,  4.33127017e+04,  5.92458796e+04,
        4.83439713e+04,  1.10249396e+05,  1.41368647e+04, -6.88598970e+02,
        2.04756593e+02,  1.69035213e+04, -8.83135987e+03, -1.20736829e+03,
       -4.79762221e+03, -3.23641805e+04,  3.67317304e+03, -5.67974067e+03,
       -1.93701030e+03,  4.50759553e+03, -4.41576915e+03, -4.77229841e+03,
        4.85420024e+02, -1.04456246e+04,  1.74223380e+03, -1.63119564e+02,
       -2.26527550e+03, -8.83135987e+03,  4.01914568e+03,  2.72111718e+03,
        1.96731226e+04, -1.29491577e+03, -2.23326896e+04,  2.59174016e+02,
       -1.58299534e+04, -8.94065973e+02,  6.04363875e+03,  4.57110969e+03,
       -1.75515473e+03, -1.32227030e+04, -6.90339253e+03, -3.32951694e+03,
       -1.32700482e+03,  5.94777863e+03, -7.75801538e+02, -1.47146557e+04,
       -1.52399387e+04, -1.57708668e+03, -6.92638405e+03, -1.04584471e+04,
        1.81985653e+03, -7.64055597e+03, -2.56255867e+03,  5.04210438e+02,
        1.72703383e+03,  2.80057103e+03,  3.93955304e+03, -3.11914269e+04,
        5.56654203e+03, -7.78227397e+03, -1.28662935e+04, -9.70059185e+03,
       -2.53443234e+04, -2.54717014e+04,  4.80840080e+04, -2.20506005e+04,
       -6.98236114e+03,  6.58474057e+03, -1.14291149e+04, -1.29558818e+04,
       -5.38727827e+03, -3.46279192e+03,  4.58474943e+02, -8.81587234e+03,
       -5.90186065e+03, -1.67328901e+03,  5.14244031e+03, -9.11936563e+03,
        2.67356298e+03, -1.16174210e+04, -6.34203139e+03, -5.51980254e+03,
        1.57794052e+03, -1.00089383e+03, -3.61897111e+03, -7.24602093e+03,
       -2.39636061e+04,  9.46893416e+03, -4.20034936e+03, -3.40180710e+03,
       -7.55167690e+03, -1.96713658e+03, -7.66164732e+03, -1.21280202e+04,
       -1.26545970e+04,  5.62213658e+03,  6.26519068e+03,  1.59814444e+03,
       -4.23612148e+04,  4.09312589e+03,  1.06484780e+04, -9.12018387e+03,
       -1.42381428e+04, -1.20727686e+04, -3.76690759e+03, -3.62854265e+03,
        6.37757990e+03,  7.41883752e+03, -3.52891918e+03, -4.52622199e+04,
        1.76075547e+04, -6.10790827e+03, -1.00623038e+04, -4.18762829e+03,
       -4.78567096e+01, -4.37692015e+03, -2.10580998e+04, -2.46541141e+03,
       -6.37270722e+01, -3.89970220e+03,  2.37055622e+03,  3.33767039e+02,
       -7.55271721e+03, -1.02376766e+04, -6.99222342e+03,  8.92387231e+04,
       -2.81498893e+04, -2.21154948e+04, -4.14592326e+04, -2.22967236e+04,
       -9.15470994e+04,  1.52362163e+04,  1.62009421e+04,  1.80112291e+04,
        1.73160947e+04, -6.10549622e+03, -1.12089520e+04, -7.46816904e+03,
       -1.31307891e+04,  1.91842352e+03,  1.42969883e+04,  2.32633153e+03,
       -8.18888936e+03, -1.27646076e+04,  8.69714104e+03, -4.83392134e+03,
       -1.31032943e+04, -6.64276656e+03,  3.37339734e+03, -2.56924408e+03,
       -8.48780240e+03, -1.70095665e+03, -8.75524490e+03])

In [399]:
y_score = reg.predict(df_test)
y_score

array([112064.83544945, 160312.06228778, 189431.67658646, ...,
       180662.16644852, 105275.86137449, 221102.38634373])

In [404]:
## Creating a Submission DataFrame
pred=pd.DataFrame(y_score)
sub_df=pd.read_csv('sample_submission.csv')
datasets=pd.concat([sub_df['Id'],pred],axis=1)
datasets.columns=['Id','SalePrice']
datasets.to_csv('sample_submission.csv',index=False)

In [405]:
foo = pd.read_csv('sample_submission.csv')
foo

        Id      SalePrice
0     1461  112064.835449
1     1462  160312.062288
2     1463  189431.676586
3     1464  196717.711136
4     1465  201976.404889
...    ...            ...
1454  2915   80556.317088
1455  2916   79838.547910
1456  2917  180662.166449
1457  2918  105275.861374
1458  2919  221102.386344

[1459 rows x 2 columns]